#!/bin/sh

## Test the use of modifiers on local variables & formal parameters [1.1]

${TOOL} FinalRequirements.java

${TOOL} OtherModifiers.java
${TOOL} OtherModifiers2.java
${TOOL} OtherModifiers3.java
