#!/bin/bash
# TODO: uncomment the following line once the performance problem is fixed
#ulimit -t 20 # even with typechecking I shouldn't be slower than 20 seconds
ls -1 boogie_*.bpl | LC_ALL=C sort | xargs fb -pp -bc -bv=1
