#!/bin/csh

rm -rf ../_tmp_classes
mkdir ../_tmp_classes

setenv CLASSPATH `pwd`

setenv TOOLCMD "${JAVAC} -d `pwd`/../_tmp_classes"
setenv TOOLARGS ""

setenv TOOL "${TOOLCMD} ${TOOLARGS}"

./run |& sed "s|`pwd`|<TEST>|g"

rm -rf ../_tmp_classes
