#!/bin/sh -f

# use: rtest directory FLAGS

echo === ESC/Java regression test $1 ===

dir=$1
cd ${dir}
shift

flags="$*"

unset CLASSPATH
export CLASSPATH

./run -quiet -plainwarning -notrace ${flags} > out 2>&1
#./run -plainwarning -notrace ${flags} > out 2>&1

if ! diff out ans > diffs; then
  echo Failed;
  cd ..
  exit 1;
else
  rm -f out diffs
fi

cd ..
