#!/bin/sh -f

# use: rtest directory FLAGS

## echo === ESC/Java regression test $1 ===
echo -n .

dir=$1
cd ${dir}
shift

flags="$*"

./run -quiet -plainwarning -notrace -noSemicolonWarnings -nowarn Modifies ${flags} > out 2>&1
#./run -plainwarning -notrace ${flags} > out 2>&1

if ! ${DIFF} out ans > diffs; then
  echo
  echo ${dir} Failed
  cd ..
  exit 1;
else
  rm -f out diffs
fi

cd ..
