#!/bin/csh -f

# use: rtestall FLAGS

echo Executing rtestall in `pwd` using
echo "    ESCJ: $ESCJ"
echo "    ESC_CLASSPATH: $ESC_CLASSPATH"
if ( $?CLASSPATH ) then
echo "    CLASSPATH: $CLASSPATH"
endif
echo "    ESCJ_SIMPLIFY: $ESCJ_SIMPLIFY"

set errs = 0
foreach f (`grep Good alltests | awk '{print $1;}'`)
  ./rtest $f $*  || set errs = 1
end
exit $errs
