# Copyright Hewlett-Packard, 2002

runtest: # cannot run these tests yet.
	# ${ESCJ} EscJavaTest*.java
	# ${ESCJ} EscJavaBad*.java

bigtest:
	cd matrix; escjava \*.java

source:
	@echo "ERROR: this is not a legal target!"

class:
	@echo "ERROR: this is not a legal target!"

clean: 
	rm -rf *.class *~
