#!/bin/bash
#
# This script runs a the Continuum server in place of the Maven executable
#
# Mobius - Distributed Testing Subsystem - Version 0.1 - April 2008
# Copyright (c) 2008, University College Dublin and Washington University
# License: GNU Public License (GPL), which is the default license for Mobius
# Homepage: https://mobius.ucd.ie/wiki/ParallelTesting
#
# Authors: Daniel M. Zimmerman, Dermot Cochran and Joseph R. Kiniry
#
# TODO: Have server names, details and topology in a configuration file
#
# Distribution script for remote testing with Maven
# This script sits on a Continuum server and runs in place of the 'mvn' command
# e.g. mv /opt/local/bin/mvn /opt/local/bin/mvn-local; ln -s <this-script> /opt/local/bin/mvn
# see https://mobius.ucd.ie/wiki/ParallelTesting
#
# 1. Initial Set-Up
#
echo "*** Initial Setup ***"
export WORKDIR=$PWD
echo "export ESCTOOLS_ROOT="$WORKDIR > Makefile.local
make pre-maven
~/test/self_update.sh
#
# TODO: read primary and secondary server names from a configuration script
#
ssh maven@arrow.ucd.ie ./test/self_update.sh
ssh maven@athena.insttech.washington.edu ./test/self_update.sh
ssh maven@boomer.insttech.washington.edu ./test/self_update.sh
#
# 2. Run the Maven test suites concurrently
#
echo "*** Running Legacy Tests ***"
make test
echo "*** Staring arrow.ucd.ie as primary Maven server for ucd.id domain ***"
ssh maven@arrow.ucd.ie ./test/arrow.sh $*
echo "*** Starting object.ucd.ie and category.ucd.ie in parallel ***"
ssh maven@category.ucd.ie ./test/category.sh $* &
ssh maven@object.ucd.ie ./test/object.sh $*
echo "*** Starting athena.insttech.washington.edu ***"
ssh maven@athena.insttech.washington.edu ./test/run_test.sh $* &
echo "*** Starting boomer.insttech.washington,edu ***"
ssh maven@boomer.insttech.washington.edu ./test/run_test.sh $* &
echo "*** Starting voting.ucd.ie ***"
nice mvn-local $*
echo "*** Waiting for all tests to finish ***"
wait
#
# 3. Collect the test reports for viewing by Continuum
#
echo "*** Collecting Test Reports ***"
rsync maven@arrow.ucd.ie:arrow/ESCTools/target/surefire-reports/TEST-DistributedTest.xml $WORKDIR/target/surefire-reports/TEST-arrow.ucd.ie.xml
rsync maven@object.ucd.ie:object/working-directory/target/surefire-reports/TEST-DistributedTest.xml $WORKDIR/target/surefire-reports/TEST-object.ucd.ie.xml
rsync maven@category.ucd.ie:category/working-directory/target/surefire-reports/TEST-DistributedTest.xml $WORKDIR/target/surefire-reports/TEST-category.ucd.ie.xml
rsync maven@athena.insttech.washington.edu:ESCTools/target/surefire-reports/TEST-DistributedTest.xml $WORKDIR/target/surefire-reports/TEST-athena.insttech.washington.edu.xml
rsync maven@boomer.insttech.washington.edu:ESCTools/target/surefire-reports/TEST-DistributedTest.xml $WORKDIR/target/surefire-reports/TEST-boomer.insttech.washington.edu.xml