#!/bin/csh -f

foreach f (ast parser tc util filespace reader)
   echo ===== Typechecking javafe/$f/\*.java =====
   ${JAVA} -classpath ${ZIPFILE}:${CLASSPATH} javafe.tc.Print -classpath ${JDKSOURCES}:${CLASSPATH} -typecheck -noprint ${SOURCEDIRECTORY}/javafe/$f/*.java
end
