  reachable size: 2
  reachable size: 3
  reachable size: 3
  reachable size: 4
  reachable size: 5
  reachable size: 5
  reachable size: 1
  reachable size: 1
  reachable size: 1
  reachable size: 1
  reachable size: 1
  reachable size: 1
  reachable size: 1
  reachable size: 1
  reachable size: 1
  reachable size: 1
  reachable size: 4
  reachable size: 5
  reachable size: 5
