package javax.swing;

public interface ScrollPaneConstants {
    String VIEWPORT = "VIEWPORT";
    String VERTICAL_SCROLLBAR = "VERTICAL_SCROLLBAR";
    String HORIZONTAL_SCROLLBAR = "HORIZONTAL_SCROLLBAR";
    String ROW_HEADER = "ROW_HEADER";
    String COLUMN_HEADER = "COLUMN_HEADER";
    String LOWER_LEFT_CORNER = "LOWER_LEFT_CORNER";
    String LOWER_RIGHT_CORNER = "LOWER_RIGHT_CORNER";
    String UPPER_LEFT_CORNER = "UPPER_LEFT_CORNER";
    String UPPER_RIGHT_CORNER = "UPPER_RIGHT_CORNER";
    String LOWER_LEADING_CORNER = "LOWER_LEADING_CORNER";
    String LOWER_TRAILING_CORNER = "LOWER_TRAILING_CORNER";
    String UPPER_LEADING_CORNER = "UPPER_LEADING_CORNER";
    String UPPER_TRAILING_CORNER = "UPPER_TRAILING_CORNER";
    String VERTICAL_SCROLLBAR_POLICY = "VERTICAL_SCROLLBAR_POLICY";
    String HORIZONTAL_SCROLLBAR_POLICY = "HORIZONTAL_SCROLLBAR_POLICY";
    int VERTICAL_SCROLLBAR_AS_NEEDED = 20;
    int VERTICAL_SCROLLBAR_NEVER = 21;
    int VERTICAL_SCROLLBAR_ALWAYS = 22;
    int HORIZONTAL_SCROLLBAR_AS_NEEDED = 30;
    int HORIZONTAL_SCROLLBAR_NEVER = 31;
    int HORIZONTAL_SCROLLBAR_ALWAYS = 32;
}
