all: source
	$(JAVAC) -d ${CLASSDIRECTORY} *.java

full: source
	$(JAVAC) -d ${CLASSDIRECTORY} *.java

source:
	echo Nothing to do

clean: 
	rm -f *~
	rm -rf *.class ${CLASSDIRECTORY}/escjava/translate/*.class

runtest:
	echo No tests to do
