#!/usr/bin/perl -p
# @(#)$Id$

# Copyright (C) 2002 Iowa State University

# This file is part of JML

# JML is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2, or (at your option)
# any later version.

# JML is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with JML; see the file COPYING.  If not, write to
# the Free Software Foundation, 675 Mass Ave, Cambridge, MA 02139, USA.

# trim newlines (needed on cygwin)
s/\r//g;

# make URLs into links
s/\`(http:\/\/[^\'<]*)\'/\`<A HREF="$1">$1<\/A>\'/;
s/\`(ftp:\/\/[^\'<]*)\'/\`<A HREF="$1">$1<\/A>\'/;
s/^(  *)(http:\/\/[^ ]*)/$1<A HREF="$2">$2<\/A>/;
s/^(  *)(ftp:\/\/[^ ]*)/$1<A HREF="$2">$2<\/A>/;

# deal with umlauts (@"a etc.)
s/\@"a/\&#228\;/g;
s/\@"e/\&#235\;/g;
s/\@"e/\&#239\;/g;
s/\@"o/\&#246\;/g;
s/\@"u/\&#252\;/g;
#"

# make emails into mailto links
s/(jml\@cs.iastate.edu)/<A HREF="mailto:$1">$1<\/A>/;

# link grammar defs and uses
s/^<VAR>([^<]*)<\/VAR> ::=/<A NAME="$1"><VAR>$1<\/VAR><\/A> ::=/g;
s/ <VAR>([^<]*)<\/VAR>/ <A HREF="\#$1"><VAR>$1<\/VAR><\/A>/g;


