stdin:1: ,
stdin:3: =
stdin:5: ;
stdin:7: {
stdin:9: }
stdin:11: (
stdin:13: )
stdin:15: [
stdin:17: ]
stdin:19: ||
stdin:22: &&
stdin:25: |
stdin:27: ^
stdin:29: &
stdin:31: !=
stdin:34: ==
stdin:37: >=
stdin:40: >
stdin:42: <=
stdin:45: <
stdin:47: <<
stdin:50: >>
stdin:53: >>>
stdin:57: +
stdin:59: -
stdin:61: /
stdin:63: %
stdin:65: *
stdin:67: !
stdin:69: ~
stdin:71: .
stdin:73: ++
stdin:76: --
stdin:79: ?
stdin:81: :
stdin:83: *=
stdin:86: /=
stdin:89: %=
stdin:92: +=
stdin:95: -=
stdin:98: <<=
stdin:102: >>=
stdin:106: >>>=
stdin:111: &=
stdin:114: |=
stdin:117: ^=
stdin:120: IDENT (abstract)
stdin:129: IDENT (boolean)
stdin:137: IDENT (break)
stdin:143: IDENT (byte)
stdin:148: IDENT (case)
stdin:153: IDENT (catch)
stdin:159: IDENT (char)
stdin:164: IDENT (class)
stdin:170: IDENT (const)
stdin:176: IDENT (continue)
stdin:185: IDENT (default)
stdin:193: IDENT (do)
stdin:196: IDENT (double)
stdin:203: IDENT (else)
stdin:208: IDENT (extends)
stdin:216: IDENT (final)
stdin:222: IDENT (finally)
stdin:230: IDENT (float)
stdin:236: IDENT (for)
stdin:240: IDENT (goto)
stdin:245: IDENT (if)
stdin:248: IDENT (implements)
stdin:259: IDENT (import)
stdin:266: IDENT (instanceof)
stdin:277: IDENT (int)
stdin:281: IDENT (interface)
stdin:291: IDENT (long)
stdin:296: IDENT (native)
stdin:303: IDENT (new)
stdin:307: IDENT (package)
stdin:315: IDENT (private)
stdin:323: IDENT (protected)
stdin:333: IDENT (public)
stdin:340: IDENT (return)
stdin:347: IDENT (short)
stdin:353: IDENT (static)
stdin:360: IDENT (super)
stdin:366: IDENT (switch)
stdin:373: IDENT (synchronized)
stdin:386: IDENT (this)
stdin:391: IDENT (throw)
stdin:397: IDENT (throws)
stdin:404: IDENT (transient)
stdin:414: IDENT (try)
stdin:418: IDENT (void)
stdin:423: IDENT (volatile)
stdin:432: IDENT (while)
stdin:438: }
stdin:438: EOF
