#!/bin/csh -f

# use: rtestall FLAGS

echo Executing rtestall in `pwd` using
if ( $?ESCTOOLS_ROOT ) then
	echo "    ESCTOOLS_ROOT: " $ESCTOOLS_ROOT
endif
if ( $?ESCTOOLS_RELEASE ) then
	echo "    ESCTOOLS_RELEASE: " $ESCTOOLS_RELEASE
endif
echo "    ESCJ: $ESCJ"
echo "    ESC_CLASSPATH: $ESC_CLASSPATH"
if ( $?CLASSPATH ) then
echo "    CLASSPATH: $CLASSPATH"
endif
echo "    ESCJ_SIMPLIFY: $ESCJ_SIMPLIFY"
echo "    ESC_SPECS: $ESC_SPECS"

echo TESTS OMITTED: `grep Omit alltests | awk '{print $1; }'`
echo TESTS DROPPED: `grep Drop alltests | awk '{print $1; }'`
echo TESTS TO BE FIXED: `grep FIX alltests | awk '{print $1; }'`
set errs = 0
foreach f (`grep Good alltests | awk '{print $1;}'`)
  ./rtest $f $*  || set errs = 1
end
echo " "
echo Completed tests in `pwd` with errs = $errs
exit $errs
