#!/bin/csh -f

## Test binary class file reader with all sources in front end.

cd ${JAVAFE_ROOT}/java/javafe

foreach i (*.java */*.java)
  ${TOOL} -classpath ${CLASSDIRECTORY}:${DECSRCLIBRARY} $i
end
