install:
	rm -rf /proj/everest/www/personnel/Julien.Charles/downloads/ProverEditorUpdateSite
	mkdir -p /proj/everest/www/personnel/Julien.Charles/downloads/ProverEditorUpdateSite 
	cp -R * /proj/everest/www/personnel/Julien.Charles/downloads/ProverEditorUpdateSite

