#!/bin/csh -f
# usage: run FLAGS

set ARGS_TRACE = (`echo $* | sed -e 's/-notrace//g'`)

foreach n (0.0 0.5 1.0 1.5 2.0 2.5 3.0 3.5 4.0 4.5)
  echo ----- Loop $n -----
  ${ESCJ} $* -loop $n -notrace LoopX.java
end
foreach n (0.0 0.5 1.0 1.5 2.0 2.5 3.0 3.5 4.0 4.5)
  echo ----- Loop $n traceinfo -----
  ${ESCJ} ${ARGS_TRACE} -loop $n LoopX.java
end
