(jde-project-file-version "1.0")
(jde-set-variables
 '(jde-project-name "ESC/Java2")
 '(jde-javadoc-gen-link-online t)
 '(jde-make-args "-k")
 '(jde-jdk-registry (quote (("1.5" . "/System/Library/Frameworks/JavaVM.framework/Versions/1.5") ("1.4" . "/System/Library/Frameworks/JavaVM.framework/Versions/1.4"))))
 '(jde-javadoc-gen-destination-directory "~/Sandboxes/ESCTools/docs/api")
 '(jde-db-option-heap-size (quote ((16 . "megabytes") (128 . "megabytes"))))
 '(jde-run-option-enable-system-assertions t)
 '(jde-make-working-directory "~/Sandboxes/ESCTools")
 '(jde-db-option-host "localhost")
 '(jde-import-insert-group-names t)
 '(jde-db-option-verbose (quote (nil nil nil)))
 '(jde-import-default-group-name "")
 '(jde-enable-abbrev-mode t)
 '(jde-global-classpath (quote ("~/Sandboxes/ESCTools/Javafe/classfiles" "~/Sandboxes/ESCTools/Escjava/classfiles" "~/Sandboxes/ESCTools/Utils" "~/Sandboxes/ESCTools/" "~/Sandboxes/ESCTools/Utils/junit.jar" "~/Sandboxes/ESCTools/Escjava/xmlrpc-1.2-b1-modified.jar" "~/Sandboxes/ESCTools/Utils/ant.jar")))
 '(jde-find-file-regexp (quote ("*.java" "*.spec" "*.refines-java" "*.refines-spec" "*.jml" "*.j")))
 '(jde-run-working-directory "~/Sandboxes/ESCTools")
 '(jde-javadoc-gen-stylesheetfile "~/Sandboxes/ESCTools/docs/escjava.css")
 '(jde-javadoc-gen-group (quote (("Java Front-end" . "javafe.*") ("ESCJava" . "escjava.*") ("JDK 1.4 Core" . "java.*") ("JDK 1.4 Extension" . "javax.*") ("Log4j" . "org.apache.log4j.*") ("Concurrency" . "edu.oswego.cs.dl.util.concurrent.*") ("jUnit" . "junit.*"))))
 '(jde-javadoc-gen-doc-title "ESC/Java2")
 '(jde-javadoc-gen-header "<![CDATA[ESC/Java2<br />&copy; 1996-1999 Digital Equipment Corporation<br />&copy; 2002-2004 Radboud University Nijmegen and David Cok<br />&copy; 2004-2005 UCD Dublin and David Cok<br />All Rights Reserved]]>")
 '(jde-javadoc-gen-window-title "ESC/Java2")
 '(jde-compile-option-directory "~/Sandboxes/ESCTools/classfiles")
 '(jde-complete-function (quote jde-complete-in-line))
 '(jde-build-function (quote (jde-make)))
 '(jde-debugger (quote ("JDEbug")))
 '(jde-lib-directory-names (quote ("^lib" "^jars" "^jar")))
 '(jde-compile-option-source (quote ("1.4")))
 '(jde-compile-option-deprecation t)
 '(jde-javadoc-gen-footer "<![CDATA[ESC/Java2<br />&copy; 1996-1999 Digital Equipment Corporation<br />&copy; 2002-2004 Radboud University Nijmegen and David Cok<br />&copy; 2004-2005 UCD Dublin and David Cok<br />All Rights Reserved]]>")
 '(jde-run-option-enable-assertions "Everywhere")
 '(jde-compile-option-sourcepath (quote ("~/Sandboxes/ESCTools/Javafe/java" "~/Sandboxes/ESCTools/Escjava/java" "~/Sandboxes/ESCTools/Utils")))
 '(jde-compile-option-depend-switch (quote ("-Xdepend")))
 '(jde-javadoc-gen-overview "~/Sandboxes/ESCTools/docs/overview.html")
 '(jde-import-auto-collapse-imports nil)
 '(jde-sourcepath (quote ("~/Sandboxes/ESCTools/Javafe/java/" "~/Sandboxes/ESCTools/Escjava/java/")))
 '(jde-javadoc-gen-packages (quote ("sos")))
 '(jde-imenu-include-modifiers t)
 '(jde-run-option-heap-size (quote ((16 . "megabytes") (128 . "megabytes"))))
 '(jde-run-application-class "escjava.Main")
 '(jde-import-auto-sort t)
 '(jde-compile-option-debug (quote ("all" (t nil nil))))
 '(jde-import-sorted-groups (quote gor))
 '(jde-compile-option-hide-classpath t)
 '(jde-help-docsets (quote (("JDK API" "" nil) ("User (javadoc)" "~/Sandboxes/ESCTools/docs/api" nil) ("User (not javadoc)" "~/Sandboxes/ESCTools/docs/jmlapi" nil) ("User (javadoc)" "/usr/local/Java/junit/javadoc" nil) ("User (javadoc)" "/usr/local/Java/JML/javadocs" nil) ("User (javadoc)" "/usr/local/Java/JCSP/doc" nil) ("User (javadoc)" "/usr/local/Java/jakarta-regexp/docs/api" nil) ("User (javadoc)" "/usr/local/Java/jakarta-log4j/docs/api" nil) ("User (javadoc)" "/usr/local/Java/concurrent/api" nil))))
 '(jde-built-class-path (quote ("~/Sandboxes/ESCTools/Javafe/classfiles" "~/Sandboxes/ESCTools/Escjava/classfiles")))
 '(jde-compile-option-depend t)
 '(jde-project-context-switching-enabled-p nil))
