#!/bin/csh -f
# Copyright 2000, 2001, Compaq Computer Corporation


#
# Where to get binaries for escjava:
#
if ($?CLASSPATH) then
else
    setenv	CLASSPATH	"."
endif
setenv	CLASSPATH	/udir/freund/jdksrc:${CLASSES}:${CLASSPATH}


if ($?RCC_STDARGS) then
else
    setenv      RCC_STDARGS   "-nowarn Override -nowarn ThreadLocal -nowarn_package java"
endif

${JAVA} rcc.Main ${RCC_STDARGS} $* | egrep -v "\-\-\-"


