#!/bin/csh

setenv TOOLCMD "${JAVA} -mx40m javafe.test.Print -classpath `pwd`:${CLASSPATH}: -bootclasspath ${JDKBINARIES}"

setenv TOOLARGS "-noprint -typecheck"

setenv TOOL "${TOOLCMD} ${TOOLARGS}"

./run |& sed "s|`pwd`|<TEST>|g"
