/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cvc3_EmbeddedManager */

#ifndef _Included_cvc3_EmbeddedManager
#define _Included_cvc3_EmbeddedManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cvc3_EmbeddedManager
 * Method:    jniDelete
 * Signature: (Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_cvc3_EmbeddedManager_jniDelete
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
