/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cvc3_ExprMut */

#ifndef _Included_cvc3_ExprMut
#define _Included_cvc3_ExprMut
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
