/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cvc3_ExprManager */

#ifndef _Included_cvc3_ExprManager
#define _Included_cvc3_ExprManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cvc3_ExprManager
 * Method:    jniGetInputLanguage
 * Signature: (Ljava/lang/Object;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cvc3_ExprManager_jniGetInputLanguage
  (JNIEnv *, jclass, jobject);

/*
 * Class:     cvc3_ExprManager
 * Method:    jniGetOutputLanguage
 * Signature: (Ljava/lang/Object;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cvc3_ExprManager_jniGetOutputLanguage
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
