/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cvc3_Flag */

#ifndef _Included_cvc3_Flag
#define _Included_cvc3_Flag
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cvc3_Flag
 * Method:    jniIsNull
 * Signature: (Ljava/lang/Object;)Z
 */
JNIEXPORT jboolean JNICALL Java_cvc3_Flag_jniIsNull
  (JNIEnv *, jclass, jobject);

/*
 * Class:     cvc3_Flag
 * Method:    jniIsBool
 * Signature: (Ljava/lang/Object;)Z
 */
JNIEXPORT jboolean JNICALL Java_cvc3_Flag_jniIsBool
  (JNIEnv *, jclass, jobject);

/*
 * Class:     cvc3_Flag
 * Method:    jniIsInt
 * Signature: (Ljava/lang/Object;)Z
 */
JNIEXPORT jboolean JNICALL Java_cvc3_Flag_jniIsInt
  (JNIEnv *, jclass, jobject);

/*
 * Class:     cvc3_Flag
 * Method:    jniIsString
 * Signature: (Ljava/lang/Object;)Z
 */
JNIEXPORT jboolean JNICALL Java_cvc3_Flag_jniIsString
  (JNIEnv *, jclass, jobject);

/*
 * Class:     cvc3_Flag
 * Method:    jniIsStringVec
 * Signature: (Ljava/lang/Object;)Z
 */
JNIEXPORT jboolean JNICALL Java_cvc3_Flag_jniIsStringVec
  (JNIEnv *, jclass, jobject);

/*
 * Class:     cvc3_Flag
 * Method:    jniGetBool
 * Signature: (Ljava/lang/Object;)Z
 */
JNIEXPORT jboolean JNICALL Java_cvc3_Flag_jniGetBool
  (JNIEnv *, jclass, jobject);

/*
 * Class:     cvc3_Flag
 * Method:    jniGetInt
 * Signature: (Ljava/lang/Object;)I
 */
JNIEXPORT jint JNICALL Java_cvc3_Flag_jniGetInt
  (JNIEnv *, jclass, jobject);

/*
 * Class:     cvc3_Flag
 * Method:    jniGetString
 * Signature: (Ljava/lang/Object;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cvc3_Flag_jniGetString
  (JNIEnv *, jclass, jobject);

/*
 * Class:     cvc3_Flag
 * Method:    jniGetHelp
 * Signature: (Ljava/lang/Object;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cvc3_Flag_jniGetHelp
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
