/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cvc3_Op */

#ifndef _Included_cvc3_Op
#define _Included_cvc3_Op
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cvc3_Op
 * Method:    jniEquals
 * Signature: (Ljava/lang/Object;Ljava/lang/Object;)Z
 */
JNIEXPORT jboolean JNICALL Java_cvc3_Op_jniEquals
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     cvc3_Op
 * Method:    jniToString
 * Signature: (Ljava/lang/Object;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cvc3_Op_jniToString
  (JNIEnv *, jclass, jobject);

/*
 * Class:     cvc3_Op
 * Method:    jniGetExpr
 * Signature: (Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_cvc3_Op_jniGetExpr
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
