/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cvc3_TheoremMut */

#ifndef _Included_cvc3_TheoremMut
#define _Included_cvc3_TheoremMut
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
