/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cvc3_ValidityChecker */

#ifndef _Included_cvc3_ValidityChecker
#define _Included_cvc3_ValidityChecker
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cvc3_ValidityChecker
 * Method:    jniCreate1
 * Signature: ()Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_cvc3_ValidityChecker_jniCreate1
  (JNIEnv *, jclass);

/*
 * Class:     cvc3_ValidityChecker
 * Method:    jniCreate2
 * Signature: (Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_cvc3_ValidityChecker_jniCreate2
  (JNIEnv *, jclass, jobject);

/*
 * Class:     cvc3_ValidityChecker
 * Method:    jniCreateFlags
 * Signature: ()Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_cvc3_ValidityChecker_jniCreateFlags
  (JNIEnv *, jclass);

/*
 * Class:     cvc3_ValidityChecker
 * Method:    jniGetFlags
 * Signature: (Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_cvc3_ValidityChecker_jniGetFlags
  (JNIEnv *, jclass, jobject);

/*
 * Class:     cvc3_ValidityChecker
 * Method:    jniBoolType
 * Signature: (Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_cvc3_ValidityChecker_jniBoolType
  (JNIEnv *, jclass, jobject);

/*
 * Class:     cvc3_ValidityChecker
 * Method:    jniRealType
 * Signature: (Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_cvc3_ValidityChecker_jniRealType
  (JNIEnv *, jclass, jobject);

/*
 * Class:     cvc3_ValidityChecker
 * Method:    jniIntType
 * Signature: (Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_cvc3_ValidityChecker_jniIntType
  (JNIEnv *, jclass, jobject);

/*
 * Class:     cvc3_ValidityChecker
 * Method:    jniSubrangeType
 * Signature: (Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_cvc3_ValidityChecker_jniSubrangeType
  (JNIEnv *, jclass, jobject, jobject, jobject);

/*
 * Class:     cvc3_ValidityChecker
 * Method:    jniSubtypeType
 * Signature: (Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_cvc3_ValidityChecker_jniSubtypeType
  (JNIEnv *, jclass, jobject, jobject, jobject);

/*
 * Class:     cvc3_ValidityChecker
 * Method:    jniTupleType1
 * Signature: (Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_cvc3_ValidityChecker_jniTupleType1
  (JNIEnv *, jclass, jobject, jobject, jobject);

/*
 * Class:     cvc3_ValidityChecker
 * Method:    jniTupleType2
 * Signature: (Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_cvc3_ValidityChecker_jniTupleType2
  (JNIEnv *, jclass, jobject, jobject, jobject, jobject);

/*
 * Class:     cvc3_ValidityChecker
 * Method:    jniTupleType3
 * Signature: (Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_cvc3_ValidityChecker_jniTupleType3
  (JNIEnv *, jclass, jobject, jobjectArray);

/*
 * Class:     cvc3_ValidityChecker
 * Method:    jniRecordType1
 * Signature: (Ljava/lang/Object;Ljava/lang/String;Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_cvc3_ValidityChecker_jniRecordType1
  (JNIEnv *, jclass, jobject, jstring, jobject);

/*
 * Class:     cvc3_ValidityChecker
 * Method:    jniRecordType2
 * Signature: (Ljava/lang/Object;Ljava/lang/String;Ljava/lang/Object;Ljava/lang/String;Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_cvc3_ValidityChecker_jniRecordType2
  (JNIEnv *, jclass, jobject, jstring, jobject, jstring, jobject);

/*
 * Class:     cvc3_ValidityChecker
 * Method:    jniRecordType3
 * Signature: (Ljava/lang/Object;Ljava/lang/String;Ljava/lang/Object;Ljava/lang/String;Ljava/lang/Object;Ljava/lang/String;Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_cvc3_ValidityChecker_jniRecordType3
  (JNIEnv *, jclass, jobject, jstring, jobject, jstring, jobject, jstring, jobject);

/*
 * Class:     cvc3_ValidityChecker
 * Method:    jniRecordType4
 * Signature: (Ljava/lang/Object;[Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_cvc3_ValidityChecker_jniRecordType4
  (JNIEnv *, jclass, jobject, jobjectArray, jobjectArray);

/*
 * Class:     cvc3_ValidityChecker
 * Method:    jniDataType1
 * Signature: (Ljava/lang/Object;Ljava/lang/String;Ljava/lang/String;[Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_cvc3_ValidityChecker_jniDataType1
  (JNIEnv *, jclass, jobject, jstring, jstring, jobjectArray, jobjectArray);

/*
 * Class:     cvc3_ValidityChecker
 * Method:    jniDataType2
 * Signature: (Ljava/lang/Object;Ljava/lang/String;[Ljava/lang/Object;[Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_cvc3_ValidityChecker_jniDataType2
  (JNIEnv *, jclass, jobject, jstring, jobjectArray, jobjectArray, jobjectArray);

/*
 * Class:     cvc3_ValidityChecker
 * Method:    jniDataType3
 * Signature: (Ljava/lang/Object;[Ljava/lang/Object;[Ljava/lang/Object;[Ljava/lang/Object;[Ljava/lang/Object;)[Ljava/lang/Object;
 */
JNIEXPORT jobjectArray JNICALL Java_cvc3_ValidityChecker_jniDataType3
  (JNIEnv *, jclass, jobject, jobjectArray, jobjectArray, jobjectArray, jobjectArray);

/*
 * Class:     cvc3_ValidityChecker
 * Method:    jniArrayType
 * Signature: (Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_cvc3_ValidityChecker_jniArrayType
  (JNIEnv *, jclass, jobject, jobject, jobject);

/*
 * Class:     cvc3_ValidityChecker
 * Method:    jniBitvecType
 * Signature: (Ljava/lang/Object;I)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_cvc3_ValidityChecker_jniBitvecType
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     cvc3_ValidityChecker
 * Method:    jniFunType1
 * Signature: (Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_cvc3_ValidityChecker_jniFunType1
  (JNIEnv *, jclass, jobject, jobject, jobject);

/*
 * Class:     cvc3_ValidityChecker
 * Method:    jniFunType2
 * Signature: (Ljava/lang/Object;[Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_cvc3_ValidityChecker_jniFunType2
  (JNIEnv *, jclass, jobject, jobjectArray, jobject);

/*
 * Class:     cvc3_ValidityChecker
 * Method:    jniCreateType1
 * Signature: (Ljava/lang/Object;Ljava/lang/String;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_cvc3_ValidityChecker_jniCreateType1
  (JNIEnv *, jclass, jobject, jstring);

/*
 * Class:     cvc3_ValidityChecker
 * Method:    jniCreateType2
 * Signature: (Ljava/lang/Object;Ljava/lang/String;Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_cvc3_ValidityChecker_jniCreateType2
  (JNIEnv *, jclass, jobject, jstring, jobject);

/*
 * Class:     cvc3_ValidityChecker
 * Method:    jniLookupType
 * Signature: (Ljava/lang/Object;Ljava/lang/String;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_cvc3_ValidityChecker_jniLookupType
  (JNIEnv *, jclass, jobject, jstring);

/*
 * Class:     cvc3_ValidityChecker
 * Method:    jniGetExprManager
 * Signature: (Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_cvc3_ValidityChecker_jniGetExprManager
  (JNIEnv *, jclass, jobject);

/*
 * Class:     cvc3_ValidityChecker
 * Method:    jniNullExpr
 * Signature: (Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_cvc3_ValidityChecker_jniNullExpr
  (JNIEnv *, jclass, jobject);

/*
 * Class:     cvc3_ValidityChecker
 * Method:    jniVarExpr1
 * Signature: (Ljava/lang/Object;Ljava/lang/String;Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_cvc3_ValidityChecker_jniVarExpr1
  (JNIEnv *, jclass, jobject, jstring, jobject);

/*
 * Class:     cvc3_ValidityChecker
 * Method:    jniVarExpr2
 * Signature: (Ljava/lang/Object;Ljava/lang/String;Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_cvc3_ValidityChecker_jniVarExpr2
  (JNIEnv *, jclass, jobject, jstring, jobject, jobject);

/*
 * Class:     cvc3_ValidityChecker
 * Method:    jniBoundVarExpr
 * Signature: (Ljava/lang/Object;Ljava/lang/String;Ljava/lang/String;Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_cvc3_ValidityChecker_jniBoundVarExpr
  (JNIEnv *, jclass, jobject, jstring, jstring, jobject);

/*
 * Class:     cvc3_ValidityChecker
 * Method:    jniLookupVar
 * Signature: (Ljava/lang/Object;Ljava/lang/String;Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_cvc3_ValidityChecker_jniLookupVar
  (JNIEnv *, jclass, jobject, jstring, jobject);

/*
 * Class:     cvc3_ValidityChecker
 * Method:    jniGetType
 * Signature: (Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_cvc3_ValidityChecker_jniGetType
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     cvc3_ValidityChecker
 * Method:    jniGetBaseType1
 * Signature: (Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_cvc3_ValidityChecker_jniGetBaseType1
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     cvc3_ValidityChecker
 * Method:    jniGetBaseType2
 * Signature: (Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_cvc3_ValidityChecker_jniGetBaseType2
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     cvc3_ValidityChecker
 * Method:    jniGetTypePred
 * Signature: (Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_cvc3_ValidityChecker_jniGetTypePred
  (JNIEnv *, jclass, jobject, jobject, jobject);

/*
 * Class:     cvc3_ValidityChecker
 * Method:    jniStringExpr
 * Signature: (Ljava/lang/Object;Ljava/lang/String;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_cvc3_ValidityChecker_jniStringExpr
  (JNIEnv *, jclass, jobject, jstring);

/*
 * Class:     cvc3_ValidityChecker
 * Method:    jniIdExpr
 * Signature: (Ljava/lang/Object;Ljava/lang/String;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_cvc3_ValidityChecker_jniIdExpr
  (JNIEnv *, jclass, jobject, jstring);

/*
 * Class:     cvc3_ValidityChecker
 * Method:    jniListExpr1
 * Signature: (Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_cvc3_ValidityChecker_jniListExpr1
  (JNIEnv *, jclass, jobject, jobjectArray);

/*
 * Class:     cvc3_ValidityChecker
 * Method:    jniListExpr2
 * Signature: (Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_cvc3_ValidityChecker_jniListExpr2
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     cvc3_ValidityChecker
 * Method:    jniListExpr3
 * Signature: (Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_cvc3_ValidityChecker_jniListExpr3
  (JNIEnv *, jclass, jobject, jobject, jobject);

/*
 * Class:     cvc3_ValidityChecker
 * Method:    jniListExpr4
 * Signature: (Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_cvc3_ValidityChecker_jniListExpr4
  (JNIEnv *, jclass, jobject, jobject, jobject, jobject);

/*
 * Class:     cvc3_ValidityChecker
 * Method:    jniListExpr5
 * Signature: (Ljava/lang/Object;Ljava/lang/String;[Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_cvc3_ValidityChecker_jniListExpr5
  (JNIEnv *, jclass, jobject, jstring, jobjectArray);

/*
 * Class:     cvc3_ValidityChecker
 * Method:    jniListExpr6
 * Signature: (Ljava/lang/Object;Ljava/lang/String;Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_cvc3_ValidityChecker_jniListExpr6
  (JNIEnv *, jclass, jobject, jstring, jobject);

/*
 * Class:     cvc3_ValidityChecker
 * Method:    jniListExpr7
 * Signature: (Ljava/lang/Object;Ljava/lang/String;Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_cvc3_ValidityChecker_jniListExpr7
  (JNIEnv *, jclass, jobject, jstring, jobject, jobject);

/*
 * Class:     cvc3_ValidityChecker
 * Method:    jniListExpr8
 * Signature: (Ljava/lang/Object;Ljava/lang/String;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_cvc3_ValidityChecker_jniListExpr8
  (JNIEnv *, jclass, jobject, jstring, jobject, jobject, jobject);

/*
 * Class:     cvc3_ValidityChecker
 * Method:    jniParseExpr
 * Signature: (Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_cvc3_ValidityChecker_jniParseExpr
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     cvc3_ValidityChecker
 * Method:    jniParseType
 * Signature: (Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_cvc3_ValidityChecker_jniParseType
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     cvc3_ValidityChecker
 * Method:    jniImportExpr
 * Signature: (Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_cvc3_ValidityChecker_jniImportExpr
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     cvc3_ValidityChecker
 * Method:    jniImportType
 * Signature: (Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_cvc3_ValidityChecker_jniImportType
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     cvc3_ValidityChecker
 * Method:    jniTrueExpr
 * Signature: (Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_cvc3_ValidityChecker_jniTrueExpr
  (JNIEnv *, jclass, jobject);

/*
 * Class:     cvc3_ValidityChecker
 * Method:    jniFalseExpr
 * Signature: (Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_cvc3_ValidityChecker_jniFalseExpr
  (JNIEnv *, jclass, jobject);

/*
 * Class:     cvc3_ValidityChecker
 * Method:    jniNotExpr
 * Signature: (Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_cvc3_ValidityChecker_jniNotExpr
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     cvc3_ValidityChecker
 * Method:    jniAndExpr1
 * Signature: (Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_cvc3_ValidityChecker_jniAndExpr1
  (JNIEnv *, jclass, jobject, jobject, jobject);

/*
 * Class:     cvc3_ValidityChecker
 * Method:    jniAndExpr2
 * Signature: (Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_cvc3_ValidityChecker_jniAndExpr2
  (JNIEnv *, jclass, jobject, jobjectArray);

/*
 * Class:     cvc3_ValidityChecker
 * Method:    jniOrExpr1
 * Signature: (Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_cvc3_ValidityChecker_jniOrExpr1
  (JNIEnv *, jclass, jobject, jobject, jobject);

/*
 * Class:     cvc3_ValidityChecker
 * Method:    jniOrExpr2
 * Signature: (Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_cvc3_ValidityChecker_jniOrExpr2
  (JNIEnv *, jclass, jobject, jobjectArray);

/*
 * Class:     cvc3_ValidityChecker
 * Method:    jniImpliesExpr
 * Signature: (Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_cvc3_ValidityChecker_jniImpliesExpr
  (JNIEnv *, jclass, jobject, jobject, jobject);

/*
 * Class:     cvc3_ValidityChecker
 * Method:    jniIffExpr
 * Signature: (Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_cvc3_ValidityChecker_jniIffExpr
  (JNIEnv *, jclass, jobject, jobject, jobject);

/*
 * Class:     cvc3_ValidityChecker
 * Method:    jniEqExpr
 * Signature: (Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_cvc3_ValidityChecker_jniEqExpr
  (JNIEnv *, jclass, jobject, jobject, jobject);

/*
 * Class:     cvc3_ValidityChecker
 * Method:    jniDistinctExpr
 * Signature: (Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_cvc3_ValidityChecker_jniDistinctExpr
  (JNIEnv *, jclass, jobject, jobjectArray);

/*
 * Class:     cvc3_ValidityChecker
 * Method:    jniIteExpr
 * Signature: (Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_cvc3_ValidityChecker_jniIteExpr
  (JNIEnv *, jclass, jobject, jobject, jobject, jobject);

/*
 * Class:     cvc3_ValidityChecker
 * Method:    jniCreateOp1
 * Signature: (Ljava/lang/Object;Ljava/lang/String;Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_cvc3_ValidityChecker_jniCreateOp1
  (JNIEnv *, jclass, jobject, jstring, jobject);

/*
 * Class:     cvc3_ValidityChecker
 * Method:    jniCreateOp2
 * Signature: (Ljava/lang/Object;Ljava/lang/String;Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_cvc3_ValidityChecker_jniCreateOp2
  (JNIEnv *, jclass, jobject, jstring, jobject, jobject);

/*
 * Class:     cvc3_ValidityChecker
 * Method:    jniEqOp
 * Signature: ()Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_cvc3_ValidityChecker_jniEqOp
  (JNIEnv *, jclass);

/*
 * Class:     cvc3_ValidityChecker
 * Method:    jniLtOp
 * Signature: ()Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_cvc3_ValidityChecker_jniLtOp
  (JNIEnv *, jclass);

/*
 * Class:     cvc3_ValidityChecker
 * Method:    jniLeOp
 * Signature: ()Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_cvc3_ValidityChecker_jniLeOp
  (JNIEnv *, jclass);

/*
 * Class:     cvc3_ValidityChecker
 * Method:    jniGtOp
 * Signature: ()Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_cvc3_ValidityChecker_jniGtOp
  (JNIEnv *, jclass);

/*
 * Class:     cvc3_ValidityChecker
 * Method:    jniGeOp
 * Signature: ()Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_cvc3_ValidityChecker_jniGeOp
  (JNIEnv *, jclass);

/*
 * Class:     cvc3_ValidityChecker
 * Method:    jniPlusOp
 * Signature: ()Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_cvc3_ValidityChecker_jniPlusOp
  (JNIEnv *, jclass);

/*
 * Class:     cvc3_ValidityChecker
 * Method:    jniMinusOp
 * Signature: ()Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_cvc3_ValidityChecker_jniMinusOp
  (JNIEnv *, jclass);

/*
 * Class:     cvc3_ValidityChecker
 * Method:    jniMultOp
 * Signature: ()Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_cvc3_ValidityChecker_jniMultOp
  (JNIEnv *, jclass);

/*
 * Class:     cvc3_ValidityChecker
 * Method:    jniDivideOp
 * Signature: ()Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_cvc3_ValidityChecker_jniDivideOp
  (JNIEnv *, jclass);

/*
 * Class:     cvc3_ValidityChecker
 * Method:    jniFunExpr1
 * Signature: (Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_cvc3_ValidityChecker_jniFunExpr1
  (JNIEnv *, jclass, jobject, jobject, jobject);

/*
 * Class:     cvc3_ValidityChecker
 * Method:    jniFunExpr2
 * Signature: (Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_cvc3_ValidityChecker_jniFunExpr2
  (JNIEnv *, jclass, jobject, jobject, jobject, jobject);

/*
 * Class:     cvc3_ValidityChecker
 * Method:    jniFunExpr3
 * Signature: (Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_cvc3_ValidityChecker_jniFunExpr3
  (JNIEnv *, jclass, jobject, jobject, jobject, jobject, jobject);

/*
 * Class:     cvc3_ValidityChecker
 * Method:    jniFunExpr4
 * Signature: (Ljava/lang/Object;Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_cvc3_ValidityChecker_jniFunExpr4
  (JNIEnv *, jclass, jobject, jobject, jobjectArray);

/*
 * Class:     cvc3_ValidityChecker
 * Method:    jniRatExpr1
 * Signature: (Ljava/lang/Object;II)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_cvc3_ValidityChecker_jniRatExpr1
  (JNIEnv *, jclass, jobject, jint, jint);

/*
 * Class:     cvc3_ValidityChecker
 * Method:    jniRatExpr2
 * Signature: (Ljava/lang/Object;Ljava/lang/String;Ljava/lang/String;I)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_cvc3_ValidityChecker_jniRatExpr2
  (JNIEnv *, jclass, jobject, jstring, jstring, jint);

/*
 * Class:     cvc3_ValidityChecker
 * Method:    jniRatExpr3
 * Signature: (Ljava/lang/Object;Ljava/lang/String;I)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_cvc3_ValidityChecker_jniRatExpr3
  (JNIEnv *, jclass, jobject, jstring, jint);

/*
 * Class:     cvc3_ValidityChecker
 * Method:    jniUminusExpr
 * Signature: (Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_cvc3_ValidityChecker_jniUminusExpr
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     cvc3_ValidityChecker
 * Method:    jniPlusExpr1
 * Signature: (Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_cvc3_ValidityChecker_jniPlusExpr1
  (JNIEnv *, jclass, jobject, jobject, jobject);

/*
 * Class:     cvc3_ValidityChecker
 * Method:    jniPlusExpr2
 * Signature: (Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_cvc3_ValidityChecker_jniPlusExpr2
  (JNIEnv *, jclass, jobject, jobjectArray);

/*
 * Class:     cvc3_ValidityChecker
 * Method:    jniMinusExpr
 * Signature: (Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_cvc3_ValidityChecker_jniMinusExpr
  (JNIEnv *, jclass, jobject, jobject, jobject);

/*
 * Class:     cvc3_ValidityChecker
 * Method:    jniMultExpr
 * Signature: (Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_cvc3_ValidityChecker_jniMultExpr
  (JNIEnv *, jclass, jobject, jobject, jobject);

/*
 * Class:     cvc3_ValidityChecker
 * Method:    jniPowExpr
 * Signature: (Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_cvc3_ValidityChecker_jniPowExpr
  (JNIEnv *, jclass, jobject, jobject, jobject);

/*
 * Class:     cvc3_ValidityChecker
 * Method:    jniDivideExpr
 * Signature: (Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_cvc3_ValidityChecker_jniDivideExpr
  (JNIEnv *, jclass, jobject, jobject, jobject);

/*
 * Class:     cvc3_ValidityChecker
 * Method:    jniLtExpr
 * Signature: (Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_cvc3_ValidityChecker_jniLtExpr
  (JNIEnv *, jclass, jobject, jobject, jobject);

/*
 * Class:     cvc3_ValidityChecker
 * Method:    jniLeExpr
 * Signature: (Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_cvc3_ValidityChecker_jniLeExpr
  (JNIEnv *, jclass, jobject, jobject, jobject);

/*
 * Class:     cvc3_ValidityChecker
 * Method:    jniGtExpr
 * Signature: (Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_cvc3_ValidityChecker_jniGtExpr
  (JNIEnv *, jclass, jobject, jobject, jobject);

/*
 * Class:     cvc3_ValidityChecker
 * Method:    jniGeExpr
 * Signature: (Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_cvc3_ValidityChecker_jniGeExpr
  (JNIEnv *, jclass, jobject, jobject, jobject);

/*
 * Class:     cvc3_ValidityChecker
 * Method:    jniRecordExpr1
 * Signature: (Ljava/lang/Object;Ljava/lang/String;Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_cvc3_ValidityChecker_jniRecordExpr1
  (JNIEnv *, jclass, jobject, jstring, jobject);

/*
 * Class:     cvc3_ValidityChecker
 * Method:    jniRecordExpr2
 * Signature: (Ljava/lang/Object;Ljava/lang/String;Ljava/lang/Object;Ljava/lang/String;Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_cvc3_ValidityChecker_jniRecordExpr2
  (JNIEnv *, jclass, jobject, jstring, jobject, jstring, jobject);

/*
 * Class:     cvc3_ValidityChecker
 * Method:    jniRecordExpr3
 * Signature: (Ljava/lang/Object;Ljava/lang/String;Ljava/lang/Object;Ljava/lang/String;Ljava/lang/Object;Ljava/lang/String;Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_cvc3_ValidityChecker_jniRecordExpr3
  (JNIEnv *, jclass, jobject, jstring, jobject, jstring, jobject, jstring, jobject);

/*
 * Class:     cvc3_ValidityChecker
 * Method:    jniRecordExpr4
 * Signature: (Ljava/lang/Object;[Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_cvc3_ValidityChecker_jniRecordExpr4
  (JNIEnv *, jclass, jobject, jobjectArray, jobjectArray);

/*
 * Class:     cvc3_ValidityChecker
 * Method:    jniRecSelectExpr
 * Signature: (Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/String;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_cvc3_ValidityChecker_jniRecSelectExpr
  (JNIEnv *, jclass, jobject, jobject, jstring);

/*
 * Class:     cvc3_ValidityChecker
 * Method:    jniRecUpdateExpr
 * Signature: (Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/String;Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_cvc3_ValidityChecker_jniRecUpdateExpr
  (JNIEnv *, jclass, jobject, jobject, jstring, jobject);

/*
 * Class:     cvc3_ValidityChecker
 * Method:    jniReadExpr
 * Signature: (Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_cvc3_ValidityChecker_jniReadExpr
  (JNIEnv *, jclass, jobject, jobject, jobject);

/*
 * Class:     cvc3_ValidityChecker
 * Method:    jniWriteExpr
 * Signature: (Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_cvc3_ValidityChecker_jniWriteExpr
  (JNIEnv *, jclass, jobject, jobject, jobject, jobject);

/*
 * Class:     cvc3_ValidityChecker
 * Method:    jniNewBVConstExpr1
 * Signature: (Ljava/lang/Object;Ljava/lang/String;I)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_cvc3_ValidityChecker_jniNewBVConstExpr1
  (JNIEnv *, jclass, jobject, jstring, jint);

/*
 * Class:     cvc3_ValidityChecker
 * Method:    jniNewBVConstExpr2
 * Signature: (Ljava/lang/Object;[Z)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_cvc3_ValidityChecker_jniNewBVConstExpr2
  (JNIEnv *, jclass, jobject, jbooleanArray);

/*
 * Class:     cvc3_ValidityChecker
 * Method:    jniNewBVConstExpr3
 * Signature: (Ljava/lang/Object;Ljava/lang/Object;I)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_cvc3_ValidityChecker_jniNewBVConstExpr3
  (JNIEnv *, jclass, jobject, jobject, jint);

/*
 * Class:     cvc3_ValidityChecker
 * Method:    jniNewConcatExpr1
 * Signature: (Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_cvc3_ValidityChecker_jniNewConcatExpr1
  (JNIEnv *, jclass, jobject, jobject, jobject);

/*
 * Class:     cvc3_ValidityChecker
 * Method:    jniNewConcatExpr2
 * Signature: (Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_cvc3_ValidityChecker_jniNewConcatExpr2
  (JNIEnv *, jclass, jobject, jobjectArray);

/*
 * Class:     cvc3_ValidityChecker
 * Method:    jniNewBVExtractExpr
 * Signature: (Ljava/lang/Object;Ljava/lang/Object;II)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_cvc3_ValidityChecker_jniNewBVExtractExpr
  (JNIEnv *, jclass, jobject, jobject, jint, jint);

/*
 * Class:     cvc3_ValidityChecker
 * Method:    jniNewBVNegExpr
 * Signature: (Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_cvc3_ValidityChecker_jniNewBVNegExpr
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     cvc3_ValidityChecker
 * Method:    jniNewBVAndExpr1
 * Signature: (Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_cvc3_ValidityChecker_jniNewBVAndExpr1
  (JNIEnv *, jclass, jobject, jobject, jobject);

/*
 * Class:     cvc3_ValidityChecker
 * Method:    jniNewBVAndExpr2
 * Signature: (Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_cvc3_ValidityChecker_jniNewBVAndExpr2
  (JNIEnv *, jclass, jobject, jobjectArray);

/*
 * Class:     cvc3_ValidityChecker
 * Method:    jniNewBVOrExpr1
 * Signature: (Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_cvc3_ValidityChecker_jniNewBVOrExpr1
  (JNIEnv *, jclass, jobject, jobject, jobject);

/*
 * Class:     cvc3_ValidityChecker
 * Method:    jniNewBVOrExpr2
 * Signature: (Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_cvc3_ValidityChecker_jniNewBVOrExpr2
  (JNIEnv *, jclass, jobject, jobjectArray);

/*
 * Class:     cvc3_ValidityChecker
 * Method:    jniNewBVXorExpr1
 * Signature: (Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_cvc3_ValidityChecker_jniNewBVXorExpr1
  (JNIEnv *, jclass, jobject, jobject, jobject);

/*
 * Class:     cvc3_ValidityChecker
 * Method:    jniNewBVXorExpr2
 * Signature: (Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_cvc3_ValidityChecker_jniNewBVXorExpr2
  (JNIEnv *, jclass, jobject, jobjectArray);

/*
 * Class:     cvc3_ValidityChecker
 * Method:    jniNewBVXnorExpr1
 * Signature: (Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_cvc3_ValidityChecker_jniNewBVXnorExpr1
  (JNIEnv *, jclass, jobject, jobject, jobject);

/*
 * Class:     cvc3_ValidityChecker
 * Method:    jniNewBVXnorExpr2
 * Signature: (Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_cvc3_ValidityChecker_jniNewBVXnorExpr2
  (JNIEnv *, jclass, jobject, jobjectArray);

/*
 * Class:     cvc3_ValidityChecker
 * Method:    jniNewBVNandExpr
 * Signature: (Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_cvc3_ValidityChecker_jniNewBVNandExpr
  (JNIEnv *, jclass, jobject, jobject, jobject);

/*
 * Class:     cvc3_ValidityChecker
 * Method:    jniNewBVNorExpr
 * Signature: (Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_cvc3_ValidityChecker_jniNewBVNorExpr
  (JNIEnv *, jclass, jobject, jobject, jobject);

/*
 * Class:     cvc3_ValidityChecker
 * Method:    jniNewBVLTExpr
 * Signature: (Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_cvc3_ValidityChecker_jniNewBVLTExpr
  (JNIEnv *, jclass, jobject, jobject, jobject);

/*
 * Class:     cvc3_ValidityChecker
 * Method:    jniNewBVLEExpr
 * Signature: (Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_cvc3_ValidityChecker_jniNewBVLEExpr
  (JNIEnv *, jclass, jobject, jobject, jobject);

/*
 * Class:     cvc3_ValidityChecker
 * Method:    jniNewBVSLTExpr
 * Signature: (Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_cvc3_ValidityChecker_jniNewBVSLTExpr
  (JNIEnv *, jclass, jobject, jobject, jobject);

/*
 * Class:     cvc3_ValidityChecker
 * Method:    jniNewBVSLEExpr
 * Signature: (Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_cvc3_ValidityChecker_jniNewBVSLEExpr
  (JNIEnv *, jclass, jobject, jobject, jobject);

/*
 * Class:     cvc3_ValidityChecker
 * Method:    jniNewSXExpr
 * Signature: (Ljava/lang/Object;Ljava/lang/Object;I)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_cvc3_ValidityChecker_jniNewSXExpr
  (JNIEnv *, jclass, jobject, jobject, jint);

/*
 * Class:     cvc3_ValidityChecker
 * Method:    jniNewBVUminusExpr
 * Signature: (Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_cvc3_ValidityChecker_jniNewBVUminusExpr
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     cvc3_ValidityChecker
 * Method:    jniNewBVSubExpr
 * Signature: (Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_cvc3_ValidityChecker_jniNewBVSubExpr
  (JNIEnv *, jclass, jobject, jobject, jobject);

/*
 * Class:     cvc3_ValidityChecker
 * Method:    jniNewBVPlusExpr
 * Signature: (Ljava/lang/Object;I[Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_cvc3_ValidityChecker_jniNewBVPlusExpr
  (JNIEnv *, jclass, jobject, jint, jobjectArray);

/*
 * Class:     cvc3_ValidityChecker
 * Method:    jniNewBVMultExpr
 * Signature: (Ljava/lang/Object;ILjava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_cvc3_ValidityChecker_jniNewBVMultExpr
  (JNIEnv *, jclass, jobject, jint, jobject, jobject);

/*
 * Class:     cvc3_ValidityChecker
 * Method:    jniNewBVUDivExpr
 * Signature: (Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_cvc3_ValidityChecker_jniNewBVUDivExpr
  (JNIEnv *, jclass, jobject, jobject, jobject);

/*
 * Class:     cvc3_ValidityChecker
 * Method:    jniNewBVURemExpr
 * Signature: (Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_cvc3_ValidityChecker_jniNewBVURemExpr
  (JNIEnv *, jclass, jobject, jobject, jobject);

/*
 * Class:     cvc3_ValidityChecker
 * Method:    jniNewBVSDivExpr
 * Signature: (Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_cvc3_ValidityChecker_jniNewBVSDivExpr
  (JNIEnv *, jclass, jobject, jobject, jobject);

/*
 * Class:     cvc3_ValidityChecker
 * Method:    jniNewBVSRemExpr
 * Signature: (Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_cvc3_ValidityChecker_jniNewBVSRemExpr
  (JNIEnv *, jclass, jobject, jobject, jobject);

/*
 * Class:     cvc3_ValidityChecker
 * Method:    jniNewBVSModExpr
 * Signature: (Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_cvc3_ValidityChecker_jniNewBVSModExpr
  (JNIEnv *, jclass, jobject, jobject, jobject);

/*
 * Class:     cvc3_ValidityChecker
 * Method:    jniNewFixedLeftShiftExpr
 * Signature: (Ljava/lang/Object;Ljava/lang/Object;I)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_cvc3_ValidityChecker_jniNewFixedLeftShiftExpr
  (JNIEnv *, jclass, jobject, jobject, jint);

/*
 * Class:     cvc3_ValidityChecker
 * Method:    jniNewFixedConstWidthLeftShiftExpr
 * Signature: (Ljava/lang/Object;Ljava/lang/Object;I)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_cvc3_ValidityChecker_jniNewFixedConstWidthLeftShiftExpr
  (JNIEnv *, jclass, jobject, jobject, jint);

/*
 * Class:     cvc3_ValidityChecker
 * Method:    jniNewFixedRightShiftExpr
 * Signature: (Ljava/lang/Object;Ljava/lang/Object;I)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_cvc3_ValidityChecker_jniNewFixedRightShiftExpr
  (JNIEnv *, jclass, jobject, jobject, jint);

/*
 * Class:     cvc3_ValidityChecker
 * Method:    jniTupleExpr
 * Signature: (Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_cvc3_ValidityChecker_jniTupleExpr
  (JNIEnv *, jclass, jobject, jobjectArray);

/*
 * Class:     cvc3_ValidityChecker
 * Method:    jniTupleSelectExpr
 * Signature: (Ljava/lang/Object;Ljava/lang/Object;I)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_cvc3_ValidityChecker_jniTupleSelectExpr
  (JNIEnv *, jclass, jobject, jobject, jint);

/*
 * Class:     cvc3_ValidityChecker
 * Method:    jniTupleUpdateExpr
 * Signature: (Ljava/lang/Object;Ljava/lang/Object;ILjava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_cvc3_ValidityChecker_jniTupleUpdateExpr
  (JNIEnv *, jclass, jobject, jobject, jint, jobject);

/*
 * Class:     cvc3_ValidityChecker
 * Method:    jniDatatypeConsExpr
 * Signature: (Ljava/lang/Object;Ljava/lang/String;[Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_cvc3_ValidityChecker_jniDatatypeConsExpr
  (JNIEnv *, jclass, jobject, jstring, jobjectArray);

/*
 * Class:     cvc3_ValidityChecker
 * Method:    jniDatatypeSelExpr
 * Signature: (Ljava/lang/Object;Ljava/lang/String;Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_cvc3_ValidityChecker_jniDatatypeSelExpr
  (JNIEnv *, jclass, jobject, jstring, jobject);

/*
 * Class:     cvc3_ValidityChecker
 * Method:    jniDatatypeTestExpr
 * Signature: (Ljava/lang/Object;Ljava/lang/String;Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_cvc3_ValidityChecker_jniDatatypeTestExpr
  (JNIEnv *, jclass, jobject, jstring, jobject);

/*
 * Class:     cvc3_ValidityChecker
 * Method:    jniForallExpr1
 * Signature: (Ljava/lang/Object;[Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_cvc3_ValidityChecker_jniForallExpr1
  (JNIEnv *, jclass, jobject, jobjectArray, jobject);

/*
 * Class:     cvc3_ValidityChecker
 * Method:    jniForallExpr2
 * Signature: (Ljava/lang/Object;[Ljava/lang/Object;Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_cvc3_ValidityChecker_jniForallExpr2
  (JNIEnv *, jclass, jobject, jobjectArray, jobject, jobjectArray);

/*
 * Class:     cvc3_ValidityChecker
 * Method:    jniSetTriggers
 * Signature: (Ljava/lang/Object;Ljava/lang/Object;[Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_cvc3_ValidityChecker_jniSetTriggers
  (JNIEnv *, jclass, jobject, jobject, jobjectArray);

/*
 * Class:     cvc3_ValidityChecker
 * Method:    jniExistsExpr
 * Signature: (Ljava/lang/Object;[Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_cvc3_ValidityChecker_jniExistsExpr
  (JNIEnv *, jclass, jobject, jobjectArray, jobject);

/*
 * Class:     cvc3_ValidityChecker
 * Method:    jniLambdaExpr
 * Signature: (Ljava/lang/Object;[Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_cvc3_ValidityChecker_jniLambdaExpr
  (JNIEnv *, jclass, jobject, jobjectArray, jobject);

/*
 * Class:     cvc3_ValidityChecker
 * Method:    jniTransClosure
 * Signature: (Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_cvc3_ValidityChecker_jniTransClosure
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     cvc3_ValidityChecker
 * Method:    jniSimulateExpr
 * Signature: (Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;[Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_cvc3_ValidityChecker_jniSimulateExpr
  (JNIEnv *, jclass, jobject, jobject, jobject, jobjectArray, jobject);

/*
 * Class:     cvc3_ValidityChecker
 * Method:    jniSetResourceLimit
 * Signature: (Ljava/lang/Object;I)V
 */
JNIEXPORT void JNICALL Java_cvc3_ValidityChecker_jniSetResourceLimit
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     cvc3_ValidityChecker
 * Method:    jniAssertFormula
 * Signature: (Ljava/lang/Object;Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_cvc3_ValidityChecker_jniAssertFormula
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     cvc3_ValidityChecker
 * Method:    jniRegisterAtom
 * Signature: (Ljava/lang/Object;Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_cvc3_ValidityChecker_jniRegisterAtom
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     cvc3_ValidityChecker
 * Method:    jniGetImpliedLiteral
 * Signature: (Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_cvc3_ValidityChecker_jniGetImpliedLiteral
  (JNIEnv *, jclass, jobject);

/*
 * Class:     cvc3_ValidityChecker
 * Method:    jniSimplify
 * Signature: (Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_cvc3_ValidityChecker_jniSimplify
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     cvc3_ValidityChecker
 * Method:    jniQuery
 * Signature: (Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cvc3_ValidityChecker_jniQuery
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     cvc3_ValidityChecker
 * Method:    jniCheckUnsat
 * Signature: (Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cvc3_ValidityChecker_jniCheckUnsat
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     cvc3_ValidityChecker
 * Method:    jniCheckContinue
 * Signature: (Ljava/lang/Object;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cvc3_ValidityChecker_jniCheckContinue
  (JNIEnv *, jclass, jobject);

/*
 * Class:     cvc3_ValidityChecker
 * Method:    jniRestart
 * Signature: (Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cvc3_ValidityChecker_jniRestart
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     cvc3_ValidityChecker
 * Method:    jniReturnFromCheck
 * Signature: (Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_cvc3_ValidityChecker_jniReturnFromCheck
  (JNIEnv *, jclass, jobject);

/*
 * Class:     cvc3_ValidityChecker
 * Method:    jniGetUserAssumptions
 * Signature: (Ljava/lang/Object;)[Ljava/lang/Object;
 */
JNIEXPORT jobjectArray JNICALL Java_cvc3_ValidityChecker_jniGetUserAssumptions
  (JNIEnv *, jclass, jobject);

/*
 * Class:     cvc3_ValidityChecker
 * Method:    jniGetInternalAssumptions
 * Signature: (Ljava/lang/Object;)[Ljava/lang/Object;
 */
JNIEXPORT jobjectArray JNICALL Java_cvc3_ValidityChecker_jniGetInternalAssumptions
  (JNIEnv *, jclass, jobject);

/*
 * Class:     cvc3_ValidityChecker
 * Method:    jniGetAssumptions
 * Signature: (Ljava/lang/Object;)[Ljava/lang/Object;
 */
JNIEXPORT jobjectArray JNICALL Java_cvc3_ValidityChecker_jniGetAssumptions
  (JNIEnv *, jclass, jobject);

/*
 * Class:     cvc3_ValidityChecker
 * Method:    jniGetAssumptionsUsed
 * Signature: (Ljava/lang/Object;)[Ljava/lang/Object;
 */
JNIEXPORT jobjectArray JNICALL Java_cvc3_ValidityChecker_jniGetAssumptionsUsed
  (JNIEnv *, jclass, jobject);

/*
 * Class:     cvc3_ValidityChecker
 * Method:    jniGetCounterExample
 * Signature: (Ljava/lang/Object;Z)[Ljava/lang/Object;
 */
JNIEXPORT jobjectArray JNICALL Java_cvc3_ValidityChecker_jniGetCounterExample
  (JNIEnv *, jclass, jobject, jboolean);

/*
 * Class:     cvc3_ValidityChecker
 * Method:    jniGetConcreteModel
 * Signature: (Ljava/lang/Object;)[Ljava/lang/Object;
 */
JNIEXPORT jobjectArray JNICALL Java_cvc3_ValidityChecker_jniGetConcreteModel
  (JNIEnv *, jclass, jobject);

/*
 * Class:     cvc3_ValidityChecker
 * Method:    jniGetValue
 * Signature: (Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cvc3_ValidityChecker_jniGetValue
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     cvc3_ValidityChecker
 * Method:    jniInconsistent1
 * Signature: (Ljava/lang/Object;)Z
 */
JNIEXPORT jboolean JNICALL Java_cvc3_ValidityChecker_jniInconsistent1
  (JNIEnv *, jclass, jobject);

/*
 * Class:     cvc3_ValidityChecker
 * Method:    jniInconsistent2
 * Signature: (Ljava/lang/Object;)[Ljava/lang/Object;
 */
JNIEXPORT jobjectArray JNICALL Java_cvc3_ValidityChecker_jniInconsistent2
  (JNIEnv *, jclass, jobject);

/*
 * Class:     cvc3_ValidityChecker
 * Method:    jniIncomplete1
 * Signature: (Ljava/lang/Object;)Z
 */
JNIEXPORT jboolean JNICALL Java_cvc3_ValidityChecker_jniIncomplete1
  (JNIEnv *, jclass, jobject);

/*
 * Class:     cvc3_ValidityChecker
 * Method:    jniIncomplete2
 * Signature: (Ljava/lang/Object;)[Ljava/lang/Object;
 */
JNIEXPORT jobjectArray JNICALL Java_cvc3_ValidityChecker_jniIncomplete2
  (JNIEnv *, jclass, jobject);

/*
 * Class:     cvc3_ValidityChecker
 * Method:    jniGetProof
 * Signature: (Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_cvc3_ValidityChecker_jniGetProof
  (JNIEnv *, jclass, jobject);

/*
 * Class:     cvc3_ValidityChecker
 * Method:    jniGetTCC
 * Signature: (Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_cvc3_ValidityChecker_jniGetTCC
  (JNIEnv *, jclass, jobject);

/*
 * Class:     cvc3_ValidityChecker
 * Method:    jniGetAssumptionsTCC
 * Signature: (Ljava/lang/Object;)[Ljava/lang/Object;
 */
JNIEXPORT jobjectArray JNICALL Java_cvc3_ValidityChecker_jniGetAssumptionsTCC
  (JNIEnv *, jclass, jobject);

/*
 * Class:     cvc3_ValidityChecker
 * Method:    jniGetProofTCC
 * Signature: (Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_cvc3_ValidityChecker_jniGetProofTCC
  (JNIEnv *, jclass, jobject);

/*
 * Class:     cvc3_ValidityChecker
 * Method:    jniGetClosure
 * Signature: (Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_cvc3_ValidityChecker_jniGetClosure
  (JNIEnv *, jclass, jobject);

/*
 * Class:     cvc3_ValidityChecker
 * Method:    jniGetProofClosure
 * Signature: (Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_cvc3_ValidityChecker_jniGetProofClosure
  (JNIEnv *, jclass, jobject);

/*
 * Class:     cvc3_ValidityChecker
 * Method:    jniStackLevel
 * Signature: (Ljava/lang/Object;)I
 */
JNIEXPORT jint JNICALL Java_cvc3_ValidityChecker_jniStackLevel
  (JNIEnv *, jclass, jobject);

/*
 * Class:     cvc3_ValidityChecker
 * Method:    jniPush
 * Signature: (Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_cvc3_ValidityChecker_jniPush
  (JNIEnv *, jclass, jobject);

/*
 * Class:     cvc3_ValidityChecker
 * Method:    jniPop
 * Signature: (Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_cvc3_ValidityChecker_jniPop
  (JNIEnv *, jclass, jobject);

/*
 * Class:     cvc3_ValidityChecker
 * Method:    jniPopTo
 * Signature: (Ljava/lang/Object;I)V
 */
JNIEXPORT void JNICALL Java_cvc3_ValidityChecker_jniPopTo
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     cvc3_ValidityChecker
 * Method:    jniScopeLevel
 * Signature: (Ljava/lang/Object;)I
 */
JNIEXPORT jint JNICALL Java_cvc3_ValidityChecker_jniScopeLevel
  (JNIEnv *, jclass, jobject);

/*
 * Class:     cvc3_ValidityChecker
 * Method:    jniPushScope
 * Signature: (Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_cvc3_ValidityChecker_jniPushScope
  (JNIEnv *, jclass, jobject);

/*
 * Class:     cvc3_ValidityChecker
 * Method:    jniPopScope
 * Signature: (Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_cvc3_ValidityChecker_jniPopScope
  (JNIEnv *, jclass, jobject);

/*
 * Class:     cvc3_ValidityChecker
 * Method:    jniPopToScope
 * Signature: (Ljava/lang/Object;I)V
 */
JNIEXPORT void JNICALL Java_cvc3_ValidityChecker_jniPopToScope
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     cvc3_ValidityChecker
 * Method:    jniGetCurrentContext
 * Signature: (Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_cvc3_ValidityChecker_jniGetCurrentContext
  (JNIEnv *, jclass, jobject);

/*
 * Class:     cvc3_ValidityChecker
 * Method:    jniLoadFile1
 * Signature: (Ljava/lang/Object;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_cvc3_ValidityChecker_jniLoadFile1
  (JNIEnv *, jclass, jobject, jstring, jstring);

/*
 * Class:     cvc3_ValidityChecker
 * Method:    jniGetStatistics
 * Signature: (Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_cvc3_ValidityChecker_jniGetStatistics
  (JNIEnv *, jclass, jobject);

/*
 * Class:     cvc3_ValidityChecker
 * Method:    jniPrintStatistics
 * Signature: (Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_cvc3_ValidityChecker_jniPrintStatistics
  (JNIEnv *, jclass, jobject);

/*
 * Class:     cvc3_ValidityChecker
 * Method:    jniSetTimeLimit
 * Signature: (Ljava/lang/Object;I)V
 */
JNIEXPORT void JNICALL Java_cvc3_ValidityChecker_jniSetTimeLimit
  (JNIEnv *, jclass, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
