#!/bin/csh -f

foreach d (java sun)

foreach f (/udir/stata/src/jdk-alpha/src/share/$d/$d/*)
	echo --- Prepping $f/\*.java ---
	${JAVA} javafe.tc.rtests.PrepTest -classpath ${CLASSPATH}:${JDKSOURCES}:/udir/stata/src/jdk-alpha/src/share/sun $f/*.java

end
end
