# Copyright 2000, 2001, Compaq Computer Corporation

.\" This file generated automatically by mtex2man(1)
.nh
.TH "rccjava" "1"
.SH "NAME"
\fBrccjava\fR \- Checks Java source files for possible race conditions
.SH "SYNOPSIS"
\fBrccjava\fR \fIoptions\fR \fIsource_filename\fR...
.SH "DESCRIPTION"
.PP
The \fBrccjava\fR command takes a list of Java source files (i.e.,
\fIfilename\fR.java) and checks the classes contained within those
files for possible race conditions.  If the \fB\-depend\fR option is supplied, then any class on which a checked class depends will also be checked.
.PP
\fITo be written...\fR
.PP
More information can be obtained from the \fBrccjava\fR user manual,
which has not yet been written.
.SH "NORMAL OPTIONS"
.PP
.PD 0
.RS 0

.TP 6
\fB\-classpath\fR \fIpath\fR
Sets the path to be used to locate user classes not supplied on the
command line to \fIpath\fR.  Overrides all previous \fB\-classpath\fR
options and the \fBCLASSPATH\fR environment variable.  The actual
classpath \fBrccjava\fR uses is the user path followed by the
bootclasspath (see \fB\-bootclasspath\fR); this allows users to add new
\&.spec files for the system classes.
and
.TP 6
\fB\-depend\fR
Normally, \fBrccjava\fR checks only the classes contained in the source
files given to it on the command line.  If the \fB\-depend\fR option is
given, however, \fBrccjava\fR also checks any classes on which those
classes depend (including indirectly).
.IP
.TP 6
\fB\-pjt\fR
Prints the Java source code with full rccjava types.
.IP
.TP 6
\fB\-agt\fR
Causes \fBrccjava\fR to assume unguarded shared fields are guarded by \fIthis\fR by default.
.IP
.TP 6
\fB\-prg\fR
Instructs \fBrccjava\fR to print guard annotations that are not required by the program.
.IP
.TP 6
\fB\-noho\fR
Instructs \fBrccjava\fR to ignore \fIholds\fR annotations.
.IP
.TP 6
\fB\-wall\fR
Instructs \fBrccjava\fR to print all warnings generated by the type checker, including those that would not be reported due to \fIno_warn\fR and \fIholds\fR annotations.
.IP
.TP 6
\fB\-pun\fR
Causes the type checker to report all  \fIno_warn\fR and \fIholds\fR annotations from the source code that are not needed.
.IP
.TP 6
\fB\-chl\fR
Instructs \fBrccjava\fR to assume that constructors hold the lock \fIthis\fR by default.  Note that this is an unsound assumption if references to \fIthis\fR escape from the constructor body.
.IP
.TP 6
\fB\-dts\fR
Causes \fBrccjava\fR to assume that all classes are \fIthread_shared\fR unless explicitly annotated as \fIthread\-local\fR. 
.IP
.TP 6
\fB\-ihl\fR
Instructs \fBrccjava\fR to assume that initializers hold the lock \fIthis\fR by default.  Note that this is an unsound assumption if references to \fIthis\fR escape from the initializer body.  In addition, static initializers are assumed to hold the lock on the class object to which the initializer belongs.
.IP
.TP 6
\fB\-nowarn\fR \fIcategory\fR
Turns off all warnings of type \fIcategory\fR.  See the
user manual for a complete list of valid categories.
.IP
.TP 6
\fB\-nowarn_package\fR \fIpackage\fR
Instructs \fBrccjava\fR  not to  print warnings caused by source files in the Java package  \fIpackage\fR.
.IP
.TP 6
\fB\-quiet\fR
Turns off display of the progress messages that \fBrccjava\fR normally
prints.
.IP
.TP 6
\fB\-warn\fR \fIcategory\fR
Turns on all warnings of type \fIcategory\fR if it is
currently turned off.  See the user manual for a complete list of valid
categories.
.IP
.TP 6
\fB\-warn_package\fR \fIpackage\fR
Prints warnings caused by source files in the Java package  \fIpackage\fR.
.PD
.IP
.PD 0
.RE
.PD
.PP
.SH "DEBUGGING OPTIONS"
.PP
These options are intended mainly for use by \fBrccjava\fR's developers,
but they may occasionally be useful to others.
.PP
.PD 0
.RS 0

.TP 6
\fB\-trace_error\fR
Prints out the call stack when a warning or error is generated.
.IP
.TP 6
\fB\-v\fR
Turn on verbose mode, which causes \fBrccjava\fR to print additional
information that may be helpful in some cases.
.PD
.IP
.PD 0
.RE
.PD
.PP
.SH "DIAGNOSTICS"
.PP
Source\-file line numbers are counted starting at 1, while column numbers
are counted starting at 0, treating tabs as one character each.  When
source is displayed, however, tabs are expanded using 8\-space tab stops.
.PP
\fITo be written...\fR
.SH "ENVIRONMENT VARIABLES"
.PP
The following environment variables affect the execution of
\fBrccjava\fR:
.PP
.PD 0
.RS 0

.TP 6
\fBCLASSPATH\fR
If set, specifies the path to be used to locate user classes not
supplied on the command line.  Defaults to the current working
directory.  The \fB\-classpath\fR option overrides this variable.  Where
to find the system classes is specified separately using the
\fB\-bootclasspath\fR option.
.IP
.TP 6
\fBRCC_STDARGS\fR
If set, specifies a set of default \fBrccjava\fR arguments.  These
arguments will be processed before any command\-line arguments.
Currently defaults to "\-nowarn Deadlock \-O1 \-O2 \-O4 \-O7 \-spvc".
.PD
.IP
.PD 0
.RE
.PD
.PP
.SH "RELATED FILES"
.PP
.PD 0
.RS 0

.TP 6
/proj/cra/pkg/rccjava/examples/
This directory contains examples of annotated code (TBD).
.PD
.IP
.PD 0
.RE
.PD
.PP
.SH "BUGS"
.PP
This is beta software; accordingly, it likely contains many bugs.
.SH "AUTHORS"
.PP
Cormac Flanagan, Compaq  (flanagan@pa.dec.com) 
.br
Stephen Freund, Compaq  (freund@pa.dec.com) 
.BR
.PP
The \fBjavafe\fR package was implemented by the \fBescjava\fR authors:  
.br
Cormac Flanagan, Compaq  (flanagan@pa.dec.com) 
.br
Rustan Leino, Compaq  (rustan@pa.dec.com) 
.br
Mark Lillibridge, Compaq  (mdl@pa.dec.com) 
.br
Greg Nelson, Compaq  (gnelson@pa.dec.com) 
.br
Jim Saxe, Compaq  (saxe@pa.dec.com) 
.br
Raymie Stata, Compaq  (stata@pa.dec.com)
.BR
.PP
.SH "SEE ALSO"
.PP
\fBCLASSPATH\fR, \fBJAVA\fR(5)
.PP
This file was generated automatically by mtex software; see the
mtex home page at http://www.research.digital.com/SRC/mtex/.
