# Copyright Hewlett-Packard, 2002

all:
	@echo "No all target exists!"

full: source
	$(JAVAC) -d ${CLASSDIRECTORY} *.java

source:
	@echo "Nothing to build."

clean: 
	rm -rf *.class ${CLASSDIRECTORY}/escjava/prover/*.class

runtest:
	@echo "No tests to run."
