#!/bin/bash
# Copyright 2001, Compaq Computer Corporation
# Copyright 2003 University of Nijmegen

# Make sure that setup.sh has been sourced.
if [ -z "${ESCJ}" ]; then
    echo "Error: setup must be sourced first"
    exit 2
fi

# If no standard arguments are set, set some escjava defaults for now.
if [ -z "${ESCJ_STDARGS}" ]; then
    ESCJ_STDARGS="-nowarn Deadlock"
fi

# If a CLASSPATH has been defined, set USERPATH to it, otherwise set
# USERPATH to '.'.
if [ -n "${CLASSPATH}" ]; then
    USERPATH=${CLASSPATH}
else
    USERPATH="."
fi

if ! [ -z ${ESC_REMOTE_DEBUG} ]; then
  JAVA_VM_DEBUG_FLAGS="-Xdebug -Xnoagent -Djava.compiler=NONE \
-Xrunjdwp:transport=dt_socket,address=8000,server=y,suspend=y"
fi

echo "Executing:"
echo "${JAVA} ${JAVA_VM_FLAGS}"
echo "  -Dsimplify=${ESCJAVA_ROOT}/simplify"
echo "  -classpath ${ESC_CLASSPATH}"
echo "  escjava.Main"
echo "  -bootclasspath ${BOOTCLASSPATH}"
echo "  -classpath ${USERPATH}"
echo "  ${ESCJ_STDARGS}"
echo "  ${@}"

JAVA_VM_FLAGS=${JAVA_VM_DEBUG_FLAGS}

${JAVA} ${JAVA_VM_FLAGS} -Dsimplify=${ESCJAVA_ROOT}/simplify \
    -classpath ${ESC_CLASSPATH} escjava.Main \
    -bootclasspath ${BOOTCLASSPATH} -classpath ${USERPATH} ${ESCJ_STDARGS} ${@}
