#!/bin/csh -f
## This script is a wrapper that sets some environment variables and then
## invokes the executable specified by ESCJ_SIMPLIFY, which should be the
## Simplify executable appropriate for the platform.

## The environment must set ESCJ_SIMPLIFY
## Typically the user sets SIMPLIFY and the escj script constructs ESCJ_SIMPLIFY

#
# Handle defaults:
#
if ($?ESCJ_SIMPLIFY_ARGS) then
else
	setenv	ESCJ_SIMPLIFY_ARGS	"-noprune -noplunge"
endif

if ($?PROVER_KILL_TIME) then
else
	setenv	PROVER_KILL_TIME	"300"
endif

if ($?PROVER_CC_LIMIT) then
else
	setenv	PROVER_CC_LIMIT		"10"
endif

${ESCJ_SIMPLIFY} ${ESCJ_SIMPLIFY_ARGS}
