% Copyright (C) 2002 Hewlett-Packard Company
% Copyright (C) 2000, 2002, Compaq Computer Corporation
% Copyright (C) 1996, Digital Equipment Corporation
% All rights reserved.
% See the file COPYRIGHT for a full description.
% Last modified on Tue Jul 16 21:18:27 PDT 2002 by saxe   
%      modified on Mon Oct 14 10:08:46 PDT 1996 by heydon 
%      modified on Thu Sep  5 16:34:03 PDT 1996 by detlefs

import		("libm3")

Generic_module	("DiGraph")
Module		("NullEdgeType")
Module		("POEdgeType")

template	("digraph")

% On systems that do not support shared libraries the following
% line (or, on some systems, the one after it) is necessary:
% option("standalone", "T")
% "build_standalone()
% Using cm3 on OS X, neither line is necessary.

Library		("DiGraph")
