# Copyright 2000, 2001, Compaq Computer Corporation

runtest:
	@echo "TESTING Javafe: test/javafe/test"
	cd lex; ${MAKE} runtest
	cd fe; ${MAKE} runtest

clean: 
	cd lex; ${MAKE} clean
	cd fe; ${MAKE} clean
