#!/bin/sh -f

# Copyright 2000, 2001, Compaq Computer Corporation

# use: rtest directory FLAGS

echo === Regression test $1 ===

dir=$1
cd ${dir}
shift

flags="$*"


unset CLASSPATH
export CLASSPATH
    
run -quiet ${flags} > out 2>&1
diff out ans > diff || echo Failed
#cp out ans
cd ..

