#!/bin/csh -f

# Checks that "Print.java print" is idempotent

# Use: TestParseIdempotent file1.java ...

set TMPA = "/tmp/tpi1"
set TMPB = "/tmp/tpi2"

  rm -rf $TMPA
  rm -rf $TMPB
  ${JAVA} javafe.test.Print -classpath ${JDK_SOURCES}:${CLASSPATH} \
        $argv[*] > $TMPA 
  ${JAVA} javafe.test.Print -classpath ${JDK_SOURCES}:${CLASSPATH} \
        -typecheck $argv[*] > $TMPB
  diff -w $TMPA $TMPB 




