#!/bin/csh -f

foreach d (java/applet java/awt java/beans java/io java/lang \
           java/math java/net java/rmi java/security java/sql sun/tools)

   echo ===== Typechecking $d/\*.java =====
   ${JAVA} -prof -classpath ${JDK_BINARIES}:${CLASSPATH} javafe.test.Print \
        -classpath ${JDK_SOURCES}:${CLASSPATH}:${JDK_BINARIES} \
        -typecheck -noprint ${JDK_SOURCES}/$d/*.java

end
