#!/proj/system/bin/tcsh -f



if ($?ESCJ) then
else
    echo "Error: setup must be sourced first"
    exit 2
endif


if ($?CLASSPATH) then
    setenv      USERPATH        ${CLASSPATH}
else
    setenv	USERPATH	"."
endif



#
# Where to get binaries for escjava:
#
setenv	CLASSPATH	${CLASSES}

${JAVA} houdini.CopyLoaded -bootclasspath ${BOOTCLASSPATH} -classpath ${USERPATH} $*
