# Copyright 2000, 2001, Compaq Computer Corporation

all:
	#echo JAVAC = ${JAVAC}
	cd jwhich; ${MAKE} 
	cd jls; ${MAKE} 
	cd jcheck; ${MAKE} 


clean:
	cd jwhich; ${MAKE} clean
	cd jls; ${MAKE} clean
	cd jcheck; ${MAKE} clean
	rm -rf *.class
