% Last modified on Thu Apr  4 11:17:14 PST 2002 by saxe  
%      modified on Mon Oct 14 09:55:23 PDT 1996 by heydon

% On some systems, the following line may be unnecessary or may need to
% be changed :
WDROOT = "../.."

override ("digraph", WDROOT)
