check:
	/Users/mikolas/SandBoxes/ESCTools/Escjava/escj -classpath "/Users/mikolas/SandBoxes/ESCTools/Javafe/classfiles:/Users/mikolas/SandBoxes/ESCTools/Escjava/classfiles:/Users/mikolas/SandBoxes/ESCTools/Utils:/Users/mikolas/SandBoxes/ESCTools/jars/mochalib.jar:/Users/mikolas/SandBoxes/ESCTools/Utils/junit.jar:/Users/mikolas/SandBoxes/ESCTools/Utils/ant.jar:/Users/mikolas/SandBoxes/ESCTools/Escjava/xmlrpc-1.2-b1-modified.jar:/Users/mikolas/java/JavaBDD/javabdd-1.0b2.jar:/sw/share/java/javacc/javacc.jar:/sw/share/java/junit/junit.jar:.:/Users/mikolas/bin/eclipse/plugins/org.junit_3.8.1/junit.jar" \
        -sourcepath "/Users/mikolas/SandBoxes/ESCTools/Javafe/java:/Users/mikolas/SandBoxes/ESCTools/Escjava/java:/Users/mikolas/SandBoxes/ESCTools/Escjava/mochalib/java:/Users/mikolas/SandBoxes/ESCTools/Utils" \
        -vclimit 1000000 \
        -source 1.4 -nosemicolonwarnings GCtoCFDBuilder.java
