Generates a list of files generated by the other templates.
It should be updated whenever the templates are modified in
a way that adds new generated files.

Almost all files in this directory are generated.

\file{generated.list}
null
ag.html
hierarchy.dot
hierarchy.gif
Evaluator.java
AssociativeEvaluator.java
Transformer.java
Substitutor.java
visitor.skeleton
\classes{\ClassName.java
}

