#!/bin/tcsh -f

if ( ! $?ESCTOOLS_ROOT ) ( echo Must define ESCTOOLS_ROOT ; exit 1 )

if ( ! $?SOURCEDIRECTORY ) setenv SOURCEDIRECTORY ${ESCTOOLS_ROOT}/Javafe/java

if ( ! $?CLASSDIRECTORY ) setenv CLASSDIRECTORY ${ESCTOOLS_ROOT}/Javafe/classfiles

echo ===== Typechecking the javafe package =====

foreach f (ast parser tc util filespace reader decsrc genericfile)
   echo ===== Typechecking javafe/$f/\*.java =====
   ${JAVA} -classpath ${CLASSDIRECTORY} javafe.test.Print \
        -classpath ${SOURCEDIRECTORY} -typecheck -noprint \
        ${SOURCEDIRECTORY}/javafe/$f/*.java
end
