#!/bin/csh

if ("$#argv" != 1) then
    echo "new: usage: new <test #>"
    exit 1
endif

mkdir test$1
chmod a+rx test$1
chmod ug+w test$1
cvs add test$1

cd test$1
cat > run <<"EOF"
#!/bin/csh -f

## It is unknown what this test does

${TOOL} files.java
"EOF"
chmod ug+xrw run
cvs add run
