#!/proj/system/bin/tcsh
setenv PROVER_KILL_TIME 500
# setenv PROVER_STATS
echo Running Simplify performance tests using the following switches: $*
echo The machine is:  ${HOST}
printenv | egrep "AXIOM|PROVER" | xargs echo Environment variables:
date
foreach f (`cat m3tests`)
  echo $f
  time /usr/bin/nice -n10 Simplify -noprune -ax esc $* $f
end
foreach f (`cat tests`)
  echo $f
  time /usr/bin/nice -n10 Simplify -noprune $* $f
end
date
