# Copyright 2000, 2001, Compaq Computer Corporation

all:
	echo "No all target exists!"

full: source
	javac -d ${CLASSDIRECTORY} *.java

source:
	echo Nothing to do

clean: 
	rm -f *~
	rm -rf *.class ${CLASSDIRECTORY}/escjava/tc/*.class

runtest:
	echo No tests to do
