all:
	echo "No all target exists!"

full: source
	$(JAVAC) -d ${CLASSDIRECTORY} *.java

source:
	echo Nothing to do

clean: 
	rm -rf *.class ${CLASSDIRECTORY}/escjava/prover/*.class

runtest:
	echo No tests to do
