#!/bin/bash
JFLAGS="-Xss64m -Xms128m -Xmx128m -ea"
if [[ "$OSTYPE" -eq cygwin ]]; then
  JFLAGS="$JFLAGS -Djline.terminal=jline.UnixTerminal"
fi
SCRIPT=`which "$0"`
HERE=`dirname "$SCRIPT"`
CP="$HERE/classes"
IFS="#"
for lib in "$HERE"/lib/*.jar; do
  CP=$CP:"$lib"
done
if [[ "$OSTYPE" -eq cygwin ]]; then
  CP=`cygpath -wp $CP`
fi
IFS=" "
#java -agentlib:hprof=cpu=samples,depth=5 $JFLAGS -cp $CP $*
java $JFLAGS -cp "$CP" "$@"

