#!/bin/bash
SCRIPT=`which $0`
HERE=`dirname $SCRIPT`
CP=$HERE/classes
for lib in `ls $HERE/lib/*.jar`; do
  CP=$CP:$lib
done
#java -agentlib:hprof=cpu=samples,depth=10 -ea -cp $CP $*
java -ea -cp $CP $*

